pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'quarkmod'

include 'grappling'
include 'excavator'
include 'loot-tweaks'
include 'large-villages'
include 'quarkmod'

project(':grappling').projectDir = file('mods/grappling')
project(':excavator').projectDir = file('mods/excavator')
project(':loot-tweaks').projectDir = file('mods/loot-tweaks')
project(':large-villages').projectDir = file('mods/large-villages')
project(':quarkmod').projectDir = file('mods/quarkmod')
