pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'quarkmod'

include 'grappling'
include 'excavator'
include 'loot-tweaks'
include 'village-builder'
include 'vampirism'
include 'dream-dimension'
include 'ancient-expansion'
include 'quarkmod'

project(':grappling').projectDir = file('mods/grappling')
project(':excavator').projectDir = file('mods/excavator')
project(':loot-tweaks').projectDir = file('mods/loot-tweaks')
project(':village-builder').projectDir = file('mods/village-builder')
project(':vampirism').projectDir = file('mods/vampirism')
project(':dream-dimension').projectDir = file('mods/dream-dimension')
project(':ancient-expansion').projectDir = file('mods/ancient-expansion')
project(':quarkmod').projectDir = file('mods/quarkmod')
